version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
    - "4306:3306"
    environment:
      MYSQL_DATABASE: "fisher"
      MYSQL_USER: "jani"
      MYSQL_PASSWORD: "EttaN1822"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - "./var/lib/mysql"
  django:
    container_name: django
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./backend:/code
    ports:
    - "8000:8000"
    depends_on:
      - db
  angular:
    container_name: angular
    build: frontend
    ports:
      - "8080:80"
