# Generated by Django 3.0.8 on 2020-07-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('persons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_species', models.CharField(blank=True, choices=[('Bream', 'Lahna'), ('Perch', 'Ahven'), ('Pike', 'Hauki'), ('Roach', 'Särki'), ('White fish', 'Siika'), ('Zander', 'Kuha'), ('Default', 'Muu'), (None, 'Ei saalista')], default=None, max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('fishing_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='fishing_stats.FishingEvent')),
            ],
        ),
    ]
