# Generated by Django 3.0.8 on 2020-08-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0003_auto_20200801_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishcatch',
            old_name='fishing_event',
            new_name='fishing_technique',
        ),
    ]
