# Generated by Django 3.0.8 on 2020-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0005_auto_20200910_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingevent',
            name='air_temperature',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fishingevent',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fishingevent',
            name='location_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fishingevent',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fishingevent',
            name='weather',
            field=models.CharField(blank=True, choices=[('snowy', 'Lumisade'), ('rainy', 'Vesisade'), ('cloydy', 'Pilvistä'), ('partly_cloudy', 'Puolipilvistä'), ('sunny', 'Aurinkoista')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fishcatch',
            name='lure',
            field=models.CharField(blank=True, choices=[('Jig', 'Jigi'), ('Spinner', 'Lippa'), ('Spoon lure', 'Lusikka'), ('Wobbler', 'Vaappu'), ('Worm', 'Mato'), (None, 'Ei viehettä')], default=None, max_length=20, null=True),
        ),
    ]
