# Generated by Django 3.0.8 on 2020-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0006_auto_20201005_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingtechnique',
            name='lure',
            field=models.CharField(blank=True, choices=[('Jig', 'Jigi'), ('Spinner', 'Lippa'), ('Spoon lure', 'Lusikka'), ('Wobbler', 'Vaappu'), ('Worm', 'Mato'), (None, 'Ei viehettä')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fishingtechnique',
            name='lure_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
