# Generated by Django 3.0.8 on 2020-10-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0007_auto_20201021_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishcatch',
            name='lure',
        ),
        migrations.RemoveField(
            model_name='fishcatch',
            name='lure_details',
        ),
    ]
