# Generated by Django 3.0.8 on 2020-10-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0008_auto_20201021_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingevent',
            name='weather',
            field=models.CharField(blank=True, choices=[('snowy', 'Lumisade'), ('rainy', 'Vesisade'), ('cloydy', 'Pilvinen '), ('partly_cloudy', 'Puolipilvinen'), ('sunny', 'Aurinkoinen')], default=None, max_length=20, null=True),
        ),
    ]
