# Generated by Django 3.0.8 on 2020-10-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0009_auto_20201022_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishcatch',
            name='fish_species',
            field=models.CharField(blank=True, choices=[('Bream', 'Lahna'), ('Perch', 'Ahven'), ('Pike', 'Hauki'), ('Roach', 'Särki'), ('Salmon', 'Lohi'), ('Trout', 'Taimen'), ('White fish', 'Siika'), ('Zander', 'Kuha'), ('Default', 'Muu')], default=None, max_length=20, null=True),
        ),
    ]
