# Generated by Django 3.0.8 on 2020-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_stats', '0010_auto_20201024_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishcatch',
            name='fish_details',
        ),
        migrations.AddField(
            model_name='fishcatch',
            name='length',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fishcatch',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
